export enum Messages {
  ProjectNotFound = 'Project does not exist',
  ProjectExists = 'Project already exists',
  IncorrectPassword = 'Password is incorrect',
  UserNotFound = 'User does not exist',
  UserExists = 'User already exists',
  EventNotFound = 'Event does not exist',
  EventExists = 'Event already exists',
  EventsSyncSuccess = 'Syncing events',
  NotAnAdmin = 'User is not an admin',
  NotASuperAdmin = 'User is not a super-admin',
  NotAMember = 'User is not a project member',
  AppIdRequired = 'APP ID is required',
  InvalidAppId = 'APP ID is invalid',
  IncorrectAppId = 'APP ID is incorrect',
  NftsSynced = 'Synced NFTs',
}
